# Generated by Django 2.0.1 on 2018-02-06 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('passwd', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('body', models.TextField(max_length=8192)),
                ('title', models.CharField(max_length=512)),
                ('tag', models.CharField(choices=[('TEAM', '팀'), ('TRIP', '여행'), ('BBS', '게시판'), ('BITCOIN', '비트코인'), ('PYTHON', '파이썬'), ('PYTHON-FRAMEWORK', '파이썬 프레임워크'), ('JSCRIPT', '자바스크립트'), ('JSCRIPT-FRAMEWORK', '자바스크립트 프레임워크'), ('CPLUS+', 'C++'), ('CPLUS+-FRAMEWORK', 'C++ 프레임워크'), ('STOCK', '주식')], max_length=64)),
                ('num_stars', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('passwd', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('body', models.TextField(max_length=8192)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
    ]
