# Generated by Django 2.0.1 on 2018-01-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='num_stars',
            field=models.IntegerField(blank=True),
        ),
    ]
