# Generated by Django 2.0.1 on 2018-01-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180130_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='num_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
