# Generated by Django 2.0.1 on 2018-01-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180130_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
