const SIDENAV_DRAWER = 'SIDENAV_DRAWER'
const ARTICLE_ITEMS = 'ARTICLE_ITEMS'
const UPDATE_ARTICLE_ITEM = 'UPDATE_ARTICLE_ITEM'
const COMMENT_ITEMS = 'COMMENT_ITEMS'
const UPDATE_COMMENT_ITEM = 'UPDATE_COMMENT_ITEM'
const DELETE_COMMENT_ITEM = 'DELETE_COMMENT_ITEM'
const ADD_COMMENT_ITEM = 'ADD_COMMENT_ITEM'
const BBS_ITEMS = 'BBS_ITEMS'
const UPDATE_BBS_ITEM = 'UPDATE_BBS_ITEM'
const ADD_BBS_ITEM = 'ADD_BBS_ITEM'
const LOADING = 'LOADING'

export default {
  SIDENAV_DRAWER,
  ARTICLE_ITEMS,
  COMMENT_ITEMS,
  LOADING,
  UPDATE_ARTICLE_ITEM,
  ADD_COMMENT_ITEM,
  UPDATE_COMMENT_ITEM,
  DELETE_COMMENT_ITEM,
  BBS_ITEMS,
  UPDATE_BBS_ITEM,
  ADD_BBS_ITEM
}
