const SIDENAV_DRAWER = 'SIDENAV_DRAWER'
const ARTICLE_ITEMS = 'ARTICLE_ITEMS'
const UPDATE_ARTICLE_ITEM = 'UPDATE_ARTICLE_ITEM'
const COMMENT_ITEMS = 'COMMENT_ITEMS'
const LOADING = 'LOADING'

export default {
  SIDENAV_DRAWER,
  ARTICLE_ITEMS,
  COMMENT_ITEMS,
  LOADING,
  UPDATE_ARTICLE_ITEM
}
